create table if not exists public.booking_drafts (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  vendor_id text not null,
  package_id text,
  draft_payload jsonb not null,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint booking_drafts_unique_user_vendor_package unique (user_id, vendor_id, package_id)
);

alter table public.booking_drafts enable row level security;

create policy "Users can view own booking drafts"
  on public.booking_drafts
  for select
  using (auth.uid() = user_id);

create policy "Users can insert own booking drafts"
  on public.booking_drafts
  for insert
  with check (auth.uid() = user_id);

create policy "Users can update own booking drafts"
  on public.booking_drafts
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete own booking drafts"
  on public.booking_drafts
  for delete
  using (auth.uid() = user_id);
